CREATE SCHEMA IF NOT EXISTS public;

COMMENT ON SCHEMA public IS 'standard public schema';

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.comments (
    id bigint NOT NULL,
    body character varying(1000) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    rating integer,
    updated_at timestamp(6) with time zone NOT NULL,
    itinerary_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT comments_rating_check CHECK (((rating <= 5) AND (rating >= 1)))
);

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: community_itinerary; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.community_itinerary (
    id bigint NOT NULL,
    country character varying(255) NOT NULL,
    cover_photo character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    days integer NOT NULL,
    estimated_cost real,
    highlights character varying(255),
    region character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    summary text NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    visibility character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT community_itinerary_days_check CHECK (((days >= 1) AND (days <= 7))),
    CONSTRAINT community_itinerary_region_check CHECK (((region)::text = ANY ((ARRAY['AFRICA'::character varying, 'AMERICAS'::character varying, 'ASIA'::character varying, 'EUROPE'::character varying, 'OCEANIA'::character varying])::text[]))),
    CONSTRAINT community_itinerary_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying])::text[])))
);


--
-- Name: community_itinerary_draft; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.community_itinerary_draft (
    id bigint NOT NULL,
    country character varying(255) NOT NULL,
    cover_photo character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    days integer,
    estimated_cost real,
    highlights character varying(255),
    region character varying(255) NOT NULL,
    slug character varying(255),
    summary text,
    title character varying(255),
    updated_at timestamp(6) with time zone,
    visibility character varying(255),
    user_id bigint NOT NULL,
    CONSTRAINT community_itinerary_draft_days_check CHECK (((days >= 1) AND (days <= 7))),
    CONSTRAINT community_itinerary_draft_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying])::text[])))
);


--
-- Name: community_itinerary_draft_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.community_itinerary_draft_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: community_itinerary_favorites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.community_itinerary_favorites (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    user_itinerary_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: community_itinerary_favorites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.community_itinerary_favorites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.community_itinerary_favorites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: community_itinerary_question_message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.community_itinerary_question_message (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    sender character varying(20) NOT NULL,
    thread_id bigint NOT NULL,
    CONSTRAINT community_itinerary_question_message_sender_check CHECK (((sender)::text = ANY ((ARRAY['TRAVELLER'::character varying, 'CREATOR'::character varying])::text[])))
);


--
-- Name: community_itinerary_question_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.community_itinerary_question_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.community_itinerary_question_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: community_itinerary_question_thread; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.community_itinerary_question_thread (
    id bigint NOT NULL,
    closed boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    asker_id bigint NOT NULL,
    community_itinerary_id bigint NOT NULL
);


--
-- Name: community_itinerary_question_thread_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.community_itinerary_question_thread ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.community_itinerary_question_thread_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: community_itinerary_schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.community_itinerary_schedule (
    community_itinerary_id bigint NOT NULL,
    day_number integer,
    day_details text,
    title character varying(255)
);


--
-- Name: community_itinerary_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.community_itinerary_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: contact_message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact_message (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255),
    message character varying(2000),
    name character varying(100)
);


--
-- Name: contact_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contact_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_verification_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_verification_tokens (
    id bigint NOT NULL,
    consumed_at timestamp(6) with time zone,
    expires_at timestamp(6) with time zone NOT NULL,
    token character varying(128) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: email_verification_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.email_verification_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_verification_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favorites (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    itinerary_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: favorites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.favorites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: itineraries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.itineraries (
    id bigint NOT NULL,
    city character varying(255) NOT NULL,
    country character varying(255) NOT NULL,
    days integer NOT NULL,
    hero character varying(255),
    price_from integer,
    region character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    summary text,
    title character varying(500) NOT NULL
);


--
-- Name: itineraries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.itineraries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itineraries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: itinerary_highlights; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.itinerary_highlights (
    itinerary_id bigint NOT NULL,
    highlights character varying(255)
);


--
-- Name: itinerary_schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.itinerary_schedule (
    itinerary_id bigint NOT NULL,
    day_number integer,
    day_details text,
    day_summary character varying(255),
    day_title character varying(255)
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    consumed_at timestamp(6) with time zone,
    expires_at timestamp(6) with time zone NOT NULL,
    token character varying(128) NOT NULL,
    used boolean NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_itinerary; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_itinerary (
    id integer NOT NULL,
    city character varying(255) NOT NULL,
    country character varying(255) NOT NULL,
    cover_photo character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    days integer NOT NULL,
    estimated_cost real,
    highlights character varying(255),
    slug character varying(255) NOT NULL,
    summary character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    visibility character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_itinerary_days_check CHECK (((days >= 1) AND (days <= 7)))
);


--
-- Name: user_itinerary_draft_schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_itinerary_draft_schedule (
    user_itinerary_id bigint NOT NULL,
    day_number integer,
    day_details text,
    title character varying(255)
);


--
-- Name: user_itinerary_draft_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_itinerary_draft_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_itinerary_schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_itinerary_schedule (
    user_itinerary_id integer NOT NULL,
    day_number integer,
    day_details character varying(255)
);


--
-- Name: user_itinerary_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_itinerary_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    adults integer,
    avatar_url character varying(255),
    bio character varying(500),
    children integer,
    currency character varying(255) NOT NULL,
    display_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    email_verified boolean NOT NULL,
    location character varying(255),
    password_hash character varying(255) NOT NULL,
    CONSTRAINT users_adults_check CHECK ((adults >= 1)),
    CONSTRAINT users_children_check CHECK ((children >= 0)),
    CONSTRAINT users_currency_check CHECK (((currency)::text = ANY ((ARRAY['USD'::character varying, 'EUR'::character varying, 'GBP'::character varying, 'AUD'::character varying, 'CAD'::character varying, 'JPY'::character varying, 'SGD'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: community_itinerary_draft community_itinerary_draft_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary_draft
    ADD CONSTRAINT community_itinerary_draft_pkey PRIMARY KEY (id);


--
-- Name: community_itinerary_favorites community_itinerary_favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary_favorites
    ADD CONSTRAINT community_itinerary_favorites_pkey PRIMARY KEY (id);


--
-- Name: community_itinerary community_itinerary_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary
    ADD CONSTRAINT community_itinerary_pkey PRIMARY KEY (id);


--
-- Name: community_itinerary_question_message community_itinerary_question_message_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary_question_message
    ADD CONSTRAINT community_itinerary_question_message_pkey PRIMARY KEY (id);


--
-- Name: community_itinerary_question_thread community_itinerary_question_thread_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary_question_thread
    ADD CONSTRAINT community_itinerary_question_thread_pkey PRIMARY KEY (id);


--
-- Name: contact_message contact_message_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_message
    ADD CONSTRAINT contact_message_pkey PRIMARY KEY (id);


--
-- Name: email_verification_tokens email_verification_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_verification_tokens
    ADD CONSTRAINT email_verification_tokens_pkey PRIMARY KEY (id);


--
-- Name: favorites favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_pkey PRIMARY KEY (id);


--
-- Name: itineraries itineraries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itineraries
    ADD CONSTRAINT itineraries_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: community_itinerary_favorites uk1rppctxcun5m1xa47ta7fkcrj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary_favorites
    ADD CONSTRAINT uk1rppctxcun5m1xa47ta7fkcrj UNIQUE (user_id, user_itinerary_id);


--
-- Name: user_itinerary uk2nx2t1ebbp40sf1vf16nrf89b; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_itinerary
    ADD CONSTRAINT uk2nx2t1ebbp40sf1vf16nrf89b UNIQUE (slug);


--
-- Name: comments uk2ps4p2wlq7xmd64ypxie3o99n; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT uk2ps4p2wlq7xmd64ypxie3o99n UNIQUE (user_id, itinerary_id);


--
-- Name: community_itinerary_draft uk5jg1s1s975no05lligncdj87o; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary_draft
    ADD CONSTRAINT uk5jg1s1s975no05lligncdj87o UNIQUE (slug);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- Name: email_verification_tokens ukewmvysc7e9y6uy7og2c21axa9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_verification_tokens
    ADD CONSTRAINT ukewmvysc7e9y6uy7og2c21axa9 UNIQUE (token);


--
-- Name: itineraries ukkh9udc9eys6e6w4s9tgw98u3s; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itineraries
    ADD CONSTRAINT ukkh9udc9eys6e6w4s9tgw98u3s UNIQUE (slug);


--
-- Name: community_itinerary ukq5cwunyuqkcywusiegrklp2by; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary
    ADD CONSTRAINT ukq5cwunyuqkcywusiegrklp2by UNIQUE (slug);


--
-- Name: favorites uksas5xvlc788mwyghahoe73n4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT uksas5xvlc788mwyghahoe73n4 UNIQUE (user_id, itinerary_id);


--
-- Name: user_itinerary user_itinerary_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_itinerary
    ADD CONSTRAINT user_itinerary_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idxla2ts67g4oh2sreayswhox1i6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idxla2ts67g4oh2sreayswhox1i6 ON public.password_reset_tokens USING btree (user_id);


--
-- Name: idxpku6mdqhdxrjueghtq3o1q3fa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idxpku6mdqhdxrjueghtq3o1q3fa ON public.email_verification_tokens USING btree (expires_at);


--
-- Name: idxs3mje1c85ftmp2uld6dt1bffs; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idxs3mje1c85ftmp2uld6dt1bffs ON public.email_verification_tokens USING btree (user_id);


--
-- Name: idxsqw3423mry4s2hjp1q9nqbkn8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idxsqw3423mry4s2hjp1q9nqbkn8 ON public.password_reset_tokens USING btree (expires_at);


--
-- Name: community_itinerary_question_message fk5bria6xcrit5ay3djwbd2973f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary_question_message
    ADD CONSTRAINT fk5bria6xcrit5ay3djwbd2973f FOREIGN KEY (thread_id) REFERENCES public.community_itinerary_question_thread(id);


--
-- Name: community_itinerary_draft fk6vxjlyaf0ixleonrbss7o0aqb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary_draft
    ADD CONSTRAINT fk6vxjlyaf0ixleonrbss7o0aqb FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_itinerary_draft_schedule fk7n4tvkxnfbejhr36uhhumanwn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_itinerary_draft_schedule
    ADD CONSTRAINT fk7n4tvkxnfbejhr36uhhumanwn FOREIGN KEY (user_itinerary_id) REFERENCES public.community_itinerary_draft(id);


--
-- Name: user_itinerary fk85a84ta86mh88mj6vqk0dkkdf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_itinerary
    ADD CONSTRAINT fk85a84ta86mh88mj6vqk0dkkdf FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: comments fk8omq0tc18jd43bu5tjh6jvraq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: community_itinerary_question_thread fka6wvjt6480mqornphlqgsypbg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary_question_thread
    ADD CONSTRAINT fka6wvjt6480mqornphlqgsypbg FOREIGN KEY (community_itinerary_id) REFERENCES public.community_itinerary(id);


--
-- Name: favorites fkc4975uqiy1r9kx31puq8wt9os; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT fkc4975uqiy1r9kx31puq8wt9os FOREIGN KEY (itinerary_id) REFERENCES public.itineraries(id);


--
-- Name: user_itinerary_schedule fkec7mep871quu81wqvl6p3daob; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_itinerary_schedule
    ADD CONSTRAINT fkec7mep871quu81wqvl6p3daob FOREIGN KEY (user_itinerary_id) REFERENCES public.user_itinerary(id);


--
-- Name: email_verification_tokens fki1c4mmamlb8keqt74k4lrtwhc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_verification_tokens
    ADD CONSTRAINT fki1c4mmamlb8keqt74k4lrtwhc FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: itinerary_schedule fkilow86sb3m3icq97sv7ylsotu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itinerary_schedule
    ADD CONSTRAINT fkilow86sb3m3icq97sv7ylsotu FOREIGN KEY (itinerary_id) REFERENCES public.itineraries(id);


--
-- Name: itinerary_highlights fkiuica3d98y103qg62fm8kj2ob; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itinerary_highlights
    ADD CONSTRAINT fkiuica3d98y103qg62fm8kj2ob FOREIGN KEY (itinerary_id) REFERENCES public.itineraries(id);


--
-- Name: community_itinerary_question_thread fkjq909k32nubquth5rqj6auftv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary_question_thread
    ADD CONSTRAINT fkjq909k32nubquth5rqj6auftv FOREIGN KEY (asker_id) REFERENCES public.users(id);


--
-- Name: password_reset_tokens fkk3ndxg5xp6v7wd4gjyusp15gq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: favorites fkk7du8b8ewipawnnpg76d55fus; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT fkk7du8b8ewipawnnpg76d55fus FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: community_itinerary fkl6guau9pwn1s48l1ho90inhh5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary
    ADD CONSTRAINT fkl6guau9pwn1s48l1ho90inhh5 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: community_itinerary_favorites fklyi79vsakw3dtlr4wij2ckmex; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary_favorites
    ADD CONSTRAINT fklyi79vsakw3dtlr4wij2ckmex FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: community_itinerary_schedule fkpeu6n1h5fv7tj1f00jtqvofp0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary_schedule
    ADD CONSTRAINT fkpeu6n1h5fv7tj1f00jtqvofp0 FOREIGN KEY (community_itinerary_id) REFERENCES public.community_itinerary(id);


--
-- Name: comments fkqj62p2aiyxhq3iucr4yh5jov3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkqj62p2aiyxhq3iucr4yh5jov3 FOREIGN KEY (itinerary_id) REFERENCES public.itineraries(id);


--
-- Name: community_itinerary_favorites fkref7odvaxem0mf2d09tc9p29h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.community_itinerary_favorites
    ADD CONSTRAINT fkref7odvaxem0mf2d09tc9p29h FOREIGN KEY (user_itinerary_id) REFERENCES public.community_itinerary(id);


--
-- PostgreSQL database dump complete
--

